version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
    driver: local
